default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 50000
  pool: 5

deploy: &deploy
  database:  dail_planner_production
  username: <%= ENV['USER_NAME'] %>
  password: <%= ENV['PS_PASS'] %>
  host: <%= ENV['rds_host'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: daily_planner_development

test:
  <<: *default
  database: daily_planner_test

staging:
  <<: *default
  <<: *deploy

production:
  <<: *default
  <<: *deploy
