default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 50000
  pool: 5

deploy: &deploy
  database: <%= ENV['rds_database'] %>
  username: <%= ENV['rds_username'] %>
  password: <%= ENV['rds_password'] %>
  host: <%= ENV['rds_host'] %>
  port: <%= ENV['rds_port'] %>

development:
  <<: *default
  database: daily_planner_development

test:
  <<: *default
  database: daily_planner_test

staging:
  <<: *default
  <<: *deploy

production:
  <<: *default
  <<: *deploy
